[project]
name = "sales-dashboard"
version = "0.1.0"
description = "Dashboard Penjualan dan Monitoring Mitra IM3"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.2.6",
    "pandas>=2.3.0",
    "streamlit>=1.45.1",
]
